from bson import ObjectId
from api.schemas.notes import Notes
from config.mongoCon import MongoCon

class NotesService:
    def get_notes():
        ...
    def post_note():
        ...
    def delete_note():
        ...
    def update_note():
        ...
